import { getStudentById, getStudents } from '@/lib/db';
import { MarkdownRenderer } from '@/components/MarkdownRenderer';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

// 生成静态参数，避免动态路由报错 (SSG)
export async function generateStaticParams() {
  const students = getStudents();
  return students.map((student) => ({
    id: student.id,
  }));
}

export default function ReportPage({ params }: { params: { id: string } }) {
  const student = getStudentById(params.id);

  if (!student) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-bg-secondary py-12 px-4 md:px-8">
      {/* Navigation */}
      <div className="max-w-[1140px] mx-auto mb-8">
        <Link href="/" className="inline-flex items-center text-text-secondary hover:text-primary transition-colors">
          <ArrowLeft size={20} className="mr-2" /> Back to Dashboard
        </Link>
      </div>

      {/* Report Container */}
      <div className="max-w-[900px] mx-auto bg-bg-primary rounded-card shadow-card overflow-hidden">
        
        {/* Header Branding */}
        <div className="bg-primary p-12 text-center relative overflow-hidden">
           {/* 装饰性背景圆 */}
          <div className="absolute top-[-50%] left-[-10%] w-[300px] h-[300px] bg-white opacity-10 rounded-full blur-3xl"></div>
          <div className="absolute bottom-[-50%] right-[-10%] w-[200px] h-[200px] bg-accent opacity-20 rounded-full blur-2xl"></div>
          
          <h1 className="text-white text-[41px] font-extrabold relative z-10">{student.name}</h1>
          <div className="inline-block mt-4 bg-accent text-text-main font-bold px-6 py-2 rounded-full relative z-10">
            ID: {student.studentId}
          </div>
          <p className="text-blue-100 mt-4 text-sm relative z-10">Milestone Achievement Report</p>
        </div>

        {/* Content Body */}
        <div className="p-8 md:p-12 lg:p-16">
          <MarkdownRenderer content={student.reportContent} />
          
          {/* Footer */}
          <div className="mt-16 pt-8 border-t border-gray-100 text-center">
            <p className="text-text-secondary text-sm">
              Generated by AI Learning Analytics • Authorized by Senior Instructor
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}